/**
 * Officeverse — Live Experience: celebration-asset storage (Phase 21 + Phase 24).
 *
 * PRIVATE storage for approved celebration videos. Bytes are served to the TV
 * through the token-authenticated state/asset endpoint, never a public URL.
 * Uploaded files are stored, never executed.
 *
 * Providers mirror the Phase-19 photo store:
 *   - "local"    → durable files under CELEBRATION_ASSET_DIR (default
 *                  ./storage/celebrations) — GoDaddy / local dev. NOT
 *                  available on Vercel (no writable filesystem), where it's
 *                  upgraded to "database" instead of silently falling back
 *                  to memory.
 *   - "database" → durable rows in the existing MySQL `storage_blobs` table
 *                  (see server/db-blob-store.ts) — the Vercel-safe
 *                  default. Selectable explicitly anywhere too.
 *   - anything else → in-memory dev store
 *
 * Path safety reuses `resolveDocumentPath` (rejects absolute keys, "..", NUL).
 * Keys are always server-generated by `celebrationAssetKey`.
 */
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { resolve, sep } from "node:path";
import { isDbConfigured } from "@/lib/db";
import { env, isVercel } from "../env";
import { DatabaseBlobStore } from "../db-blob-store";
import { resolveDocumentPath } from "../hr/salary-slip-storage";

export interface AssetStore {
  readonly kind: string;
  put(key: string, bytes: Uint8Array): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
  deleteKey(key: string): Promise<void>;
}

class MemoryAssetStore implements AssetStore {
  readonly kind = "memory";
  private readonly map = new Map<string, Uint8Array>();
  async put(key: string, bytes: Uint8Array): Promise<void> {
    if (/(^|[\\/])\.\.([\\/]|$)/.test(key) || key.startsWith("/")) throw new Error("invalid key");
    this.map.set(key, Uint8Array.from(bytes));
  }
  async get(key: string): Promise<Uint8Array | null> {
    const v = this.map.get(key);
    return v ? Uint8Array.from(v) : null;
  }
  async deleteKey(key: string): Promise<void> {
    this.map.delete(key);
  }
}

class FilesystemAssetStore implements AssetStore {
  readonly kind = "filesystem";
  constructor(private readonly root: string) {}
  private path(key: string): string {
    return resolveDocumentPath(this.root, key);
  }
  async put(key: string, bytes: Uint8Array): Promise<void> {
    const abs = this.path(key);
    await mkdir(abs.slice(0, abs.lastIndexOf(sep)), { recursive: true });
    await writeFile(abs, Buffer.from(bytes));
  }
  async get(key: string): Promise<Uint8Array | null> {
    try {
      return new Uint8Array(await readFile(this.path(key)));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
      throw err;
    }
  }
  async deleteKey(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }
}

let cached: { key: string; store: AssetStore } | null = null;

function resolveBackend(): { kind: "local" | "database" | "memory"; cacheKey: string } {
  const provider = (env("CELEBRATION_STORAGE") ?? env("PHOTO_STORAGE") ?? "local").toLowerCase();
  if (provider === "database") return { kind: "database", cacheKey: "database" };
  if (provider === "local") {
    // Same Vercel guard as the photo store: no writable filesystem outside
    // /tmp, so "local" would otherwise mkdir under process.cwd() (/var/task)
    // and throw ENOENT. Upgrade to the durable database-backed store instead
    // of silently falling back to memory (which a cold start can drop) —
    // only when the DB itself isn't configured either does this use memory,
    // so an upload never crashes even in that dead-end state.
    if (isVercel()) {
      if (isDbConfigured()) return { kind: "database", cacheKey: "database" };
      console.warn(
        "[asset-storage] local celebration-asset storage is not supported on Vercel and no database is configured — using the in-memory store (uploads will NOT survive a cold start).",
      );
      return { kind: "memory", cacheKey: "memory" };
    }
    const root = env("CELEBRATION_ASSET_DIR") ?? "./storage/celebrations";
    return { kind: "local", cacheKey: `local:${root}` };
  }
  return { kind: "memory", cacheKey: "memory" };
}

export function getAssetStore(): AssetStore {
  const { kind, cacheKey } = resolveBackend();
  if (cached && cached.key === cacheKey) return cached.store;
  const root = env("CELEBRATION_ASSET_DIR") ?? "./storage/celebrations";
  const store: AssetStore =
    kind === "local"
      ? new FilesystemAssetStore(resolve(root))
      : kind === "database"
        ? new DatabaseBlobStore()
        : new MemoryAssetStore();
  cached = { key: cacheKey, store };
  return store;
}

export function __resetAssetStore(): void {
  cached = null;
}

export function describeAssetStorage(): { provider: string; durable: boolean } {
  const { kind } = resolveBackend();
  return { provider: kind, durable: kind !== "memory" };
}

/** Server-generated storage key: `celebrations/<category>/<id>-<safeName>`. */
export function celebrationAssetKey(
  category: string,
  assetId: number,
  safeName: string,
  ext: string,
): string {
  const cat = category.replace(/[^A-Z]/gi, "").toUpperCase() || "MISC";
  const base =
    safeName
      .replace(/\.[^.]*$/, "")
      .replace(/[^A-Za-z0-9_-]+/g, "_")
      .slice(0, 40) || "clip";
  return `celebrations/${cat}/${assetId}-${base}.${ext}`;
}
