/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as OfficeTvRouteImport } from './routes/office-tv'
import { Route as ShellAssignmentsRouteImport } from './routes/_shell.assignments'
import { Route as ShellAttendanceRouteImport } from './routes/_shell.attendance'
import { Route as ShellAuditRouteImport } from './routes/_shell.audit'
import { Route as ShellCloserHubRouteImport } from './routes/_shell.closer-hub'
import { Route as ShellCompanyRouteImport } from './routes/_shell.company'
import { Route as ShellEmployeesRouteImport } from './routes/_shell.employees'
import { Route as ShellExportsRouteImport } from './routes/_shell.exports'
import { Route as ShellHolidaysRouteImport } from './routes/_shell.holidays'
import { Route as ShellImportsRouteImport } from './routes/_shell.imports'
import { Route as ShellIncentivesRouteImport } from './routes/_shell.incentives'
import { Route as ShellLeaderboardRouteImport } from './routes/_shell.leaderboard'
import { Route as ShellLeaveRouteImport } from './routes/_shell.leave'
import { Route as ShellLiveRouteImport } from './routes/_shell.live'
import { Route as ShellMissionControlRouteImport } from './routes/_shell.mission-control'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellOfficeNetworksRouteImport } from './routes/_shell.office-networks'
import { Route as ShellOperationsRouteImport } from './routes/_shell.operations'
import { Route as ShellPayrollRouteImport } from './routes/_shell.payroll'
import { Route as ShellPeopleRouteImport } from './routes/_shell.people'
import { Route as ShellPerformanceRouteImport } from './routes/_shell.performance'
import { Route as ShellPoliciesRouteImport } from './routes/_shell.policies'
import { Route as ShellPresenceRouteImport } from './routes/_shell.presence'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellScoringRouteImport } from './routes/_shell.scoring'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellShiftsRouteImport } from './routes/_shell.shifts'
import { Route as ShellTeamRouteImport } from './routes/_shell.team'
import { Route as ShellWorkspaceRouteImport } from './routes/_shell.workspace'
import { Route as ShellAgentsIndexRouteImport } from './routes/_shell.agents.index'
import { Route as ShellAgentsNewRouteImport } from './routes/_shell.agents.new'
import { Route as ShellClientsIndexRouteImport } from './routes/_shell.clients.index'
import { Route as ShellClientsNewRouteImport } from './routes/_shell.clients.new'
import { Route as ShellClosersIndexRouteImport } from './routes/_shell.closers.index'
import { Route as ShellClosersNewRouteImport } from './routes/_shell.closers.new'
import { Route as ShellFollowupsIndexRouteImport } from './routes/_shell.followups.index'
import { Route as ShellFollowupsFollowUpIdRouteImport } from './routes/_shell.followups.$followUpId'
import { Route as ShellLeadsIndexRouteImport } from './routes/_shell.leads.index'
import { Route as ShellLeadsLeadIdRouteImport } from './routes/_shell.leads.$leadId'
import { Route as ShellLeadsNewRouteImport } from './routes/_shell.leads.new'
import { Route as ApiDiagLoginRouteImport } from './routes/api/diag/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeTvRoute = OfficeTvRouteImport.update({
  id: '/office-tv',
  path: '/office-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAssignmentsRoute = ShellAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAttendanceRoute = ShellAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuditRoute = ShellAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCloserHubRoute = ShellCloserHubRouteImport.update({
  id: '/closer-hub',
  path: '/closer-hub',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCompanyRoute = ShellCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEmployeesRoute = ShellEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExportsRoute = ShellExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHolidaysRoute = ShellHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => ShellRoute,
} as any)
const ShellImportsRoute = ShellImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIncentivesRoute = ShellIncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeaderboardRoute = ShellLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeaveRoute = ShellLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLiveRoute = ShellLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMissionControlRoute = ShellMissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOfficeNetworksRoute = ShellOfficeNetworksRouteImport.update({
  id: '/office-networks',
  path: '/office-networks',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOperationsRoute = ShellOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPayrollRoute = ShellPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPeopleRoute = ShellPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPerformanceRoute = ShellPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPoliciesRoute = ShellPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPresenceRoute = ShellPresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScoringRoute = ShellScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellShiftsRoute = ShellShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTeamRoute = ShellTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkspaceRoute = ShellWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAgentsIndexRoute = ShellAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAgentsNewRoute = ShellAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClientsIndexRoute = ShellClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClientsNewRoute = ShellClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClosersIndexRoute = ShellClosersIndexRouteImport.update({
  id: '/closers/',
  path: '/closers/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClosersNewRoute = ShellClosersNewRouteImport.update({
  id: '/closers/new',
  path: '/closers/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFollowupsIndexRoute = ShellFollowupsIndexRouteImport.update({
  id: '/followups/',
  path: '/followups/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFollowupsFollowUpIdRoute =
  ShellFollowupsFollowUpIdRouteImport.update({
    id: '/followups/$followUpId',
    path: '/followups/$followUpId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellLeadsIndexRoute = ShellLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeadsLeadIdRoute = ShellLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeadsNewRoute = ShellLeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => ShellRoute,
} as any)
const ApiDiagLoginRoute = ApiDiagLoginRouteImport.update({
  id: '/api/diag/login',
  path: '/api/diag/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/office-tv': typeof OfficeTvRoute
  '/assignments': typeof ShellAssignmentsRoute
  '/attendance': typeof ShellAttendanceRoute
  '/audit': typeof ShellAuditRoute
  '/closer-hub': typeof ShellCloserHubRoute
  '/company': typeof ShellCompanyRoute
  '/employees': typeof ShellEmployeesRoute
  '/exports': typeof ShellExportsRoute
  '/holidays': typeof ShellHolidaysRoute
  '/imports': typeof ShellImportsRoute
  '/incentives': typeof ShellIncentivesRoute
  '/leaderboard': typeof ShellLeaderboardRoute
  '/leave': typeof ShellLeaveRoute
  '/live': typeof ShellLiveRoute
  '/mission-control': typeof ShellMissionControlRoute
  '/notifications': typeof ShellNotificationsRoute
  '/office-networks': typeof ShellOfficeNetworksRoute
  '/operations': typeof ShellOperationsRoute
  '/payroll': typeof ShellPayrollRoute
  '/people': typeof ShellPeopleRoute
  '/performance': typeof ShellPerformanceRoute
  '/policies': typeof ShellPoliciesRoute
  '/presence': typeof ShellPresenceRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/scoring': typeof ShellScoringRoute
  '/settings': typeof ShellSettingsRoute
  '/shifts': typeof ShellShiftsRoute
  '/team': typeof ShellTeamRoute
  '/workspace': typeof ShellWorkspaceRoute
  '/agents/new': typeof ShellAgentsNewRoute
  '/clients/new': typeof ShellClientsNewRoute
  '/closers/new': typeof ShellClosersNewRoute
  '/followups/$followUpId': typeof ShellFollowupsFollowUpIdRoute
  '/leads/$leadId': typeof ShellLeadsLeadIdRoute
  '/leads/new': typeof ShellLeadsNewRoute
  '/api/diag/login': typeof ApiDiagLoginRoute
  '/agents/': typeof ShellAgentsIndexRoute
  '/clients/': typeof ShellClientsIndexRoute
  '/closers/': typeof ShellClosersIndexRoute
  '/followups/': typeof ShellFollowupsIndexRoute
  '/leads/': typeof ShellLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/office-tv': typeof OfficeTvRoute
  '/assignments': typeof ShellAssignmentsRoute
  '/attendance': typeof ShellAttendanceRoute
  '/audit': typeof ShellAuditRoute
  '/closer-hub': typeof ShellCloserHubRoute
  '/company': typeof ShellCompanyRoute
  '/employees': typeof ShellEmployeesRoute
  '/exports': typeof ShellExportsRoute
  '/holidays': typeof ShellHolidaysRoute
  '/imports': typeof ShellImportsRoute
  '/incentives': typeof ShellIncentivesRoute
  '/leaderboard': typeof ShellLeaderboardRoute
  '/leave': typeof ShellLeaveRoute
  '/live': typeof ShellLiveRoute
  '/mission-control': typeof ShellMissionControlRoute
  '/notifications': typeof ShellNotificationsRoute
  '/office-networks': typeof ShellOfficeNetworksRoute
  '/operations': typeof ShellOperationsRoute
  '/payroll': typeof ShellPayrollRoute
  '/people': typeof ShellPeopleRoute
  '/performance': typeof ShellPerformanceRoute
  '/policies': typeof ShellPoliciesRoute
  '/presence': typeof ShellPresenceRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/scoring': typeof ShellScoringRoute
  '/settings': typeof ShellSettingsRoute
  '/shifts': typeof ShellShiftsRoute
  '/team': typeof ShellTeamRoute
  '/workspace': typeof ShellWorkspaceRoute
  '/agents/new': typeof ShellAgentsNewRoute
  '/clients/new': typeof ShellClientsNewRoute
  '/closers/new': typeof ShellClosersNewRoute
  '/followups/$followUpId': typeof ShellFollowupsFollowUpIdRoute
  '/leads/$leadId': typeof ShellLeadsLeadIdRoute
  '/leads/new': typeof ShellLeadsNewRoute
  '/api/diag/login': typeof ApiDiagLoginRoute
  '/agents': typeof ShellAgentsIndexRoute
  '/clients': typeof ShellClientsIndexRoute
  '/closers': typeof ShellClosersIndexRoute
  '/followups': typeof ShellFollowupsIndexRoute
  '/leads': typeof ShellLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/office-tv': typeof OfficeTvRoute
  '/_shell/assignments': typeof ShellAssignmentsRoute
  '/_shell/attendance': typeof ShellAttendanceRoute
  '/_shell/audit': typeof ShellAuditRoute
  '/_shell/closer-hub': typeof ShellCloserHubRoute
  '/_shell/company': typeof ShellCompanyRoute
  '/_shell/employees': typeof ShellEmployeesRoute
  '/_shell/exports': typeof ShellExportsRoute
  '/_shell/holidays': typeof ShellHolidaysRoute
  '/_shell/imports': typeof ShellImportsRoute
  '/_shell/incentives': typeof ShellIncentivesRoute
  '/_shell/leaderboard': typeof ShellLeaderboardRoute
  '/_shell/leave': typeof ShellLeaveRoute
  '/_shell/live': typeof ShellLiveRoute
  '/_shell/mission-control': typeof ShellMissionControlRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/office-networks': typeof ShellOfficeNetworksRoute
  '/_shell/operations': typeof ShellOperationsRoute
  '/_shell/payroll': typeof ShellPayrollRoute
  '/_shell/people': typeof ShellPeopleRoute
  '/_shell/performance': typeof ShellPerformanceRoute
  '/_shell/policies': typeof ShellPoliciesRoute
  '/_shell/presence': typeof ShellPresenceRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/scoring': typeof ShellScoringRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/shifts': typeof ShellShiftsRoute
  '/_shell/team': typeof ShellTeamRoute
  '/_shell/workspace': typeof ShellWorkspaceRoute
  '/_shell/agents/new': typeof ShellAgentsNewRoute
  '/_shell/clients/new': typeof ShellClientsNewRoute
  '/_shell/closers/new': typeof ShellClosersNewRoute
  '/_shell/followups/$followUpId': typeof ShellFollowupsFollowUpIdRoute
  '/_shell/leads/$leadId': typeof ShellLeadsLeadIdRoute
  '/_shell/leads/new': typeof ShellLeadsNewRoute
  '/api/diag/login': typeof ApiDiagLoginRoute
  '/_shell/agents/': typeof ShellAgentsIndexRoute
  '/_shell/clients/': typeof ShellClientsIndexRoute
  '/_shell/closers/': typeof ShellClosersIndexRoute
  '/_shell/followups/': typeof ShellFollowupsIndexRoute
  '/_shell/leads/': typeof ShellLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/office-tv'
    | '/assignments'
    | '/attendance'
    | '/audit'
    | '/closer-hub'
    | '/company'
    | '/employees'
    | '/exports'
    | '/holidays'
    | '/imports'
    | '/incentives'
    | '/leaderboard'
    | '/leave'
    | '/live'
    | '/mission-control'
    | '/notifications'
    | '/office-networks'
    | '/operations'
    | '/payroll'
    | '/people'
    | '/performance'
    | '/policies'
    | '/presence'
    | '/profile'
    | '/reports'
    | '/scoring'
    | '/settings'
    | '/shifts'
    | '/team'
    | '/workspace'
    | '/agents/new'
    | '/clients/new'
    | '/closers/new'
    | '/followups/$followUpId'
    | '/leads/$leadId'
    | '/leads/new'
    | '/api/diag/login'
    | '/agents/'
    | '/clients/'
    | '/closers/'
    | '/followups/'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/office-tv'
    | '/assignments'
    | '/attendance'
    | '/audit'
    | '/closer-hub'
    | '/company'
    | '/employees'
    | '/exports'
    | '/holidays'
    | '/imports'
    | '/incentives'
    | '/leaderboard'
    | '/leave'
    | '/live'
    | '/mission-control'
    | '/notifications'
    | '/office-networks'
    | '/operations'
    | '/payroll'
    | '/people'
    | '/performance'
    | '/policies'
    | '/presence'
    | '/profile'
    | '/reports'
    | '/scoring'
    | '/settings'
    | '/shifts'
    | '/team'
    | '/workspace'
    | '/agents/new'
    | '/clients/new'
    | '/closers/new'
    | '/followups/$followUpId'
    | '/leads/$leadId'
    | '/leads/new'
    | '/api/diag/login'
    | '/agents'
    | '/clients'
    | '/closers'
    | '/followups'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/office-tv'
    | '/_shell/assignments'
    | '/_shell/attendance'
    | '/_shell/audit'
    | '/_shell/closer-hub'
    | '/_shell/company'
    | '/_shell/employees'
    | '/_shell/exports'
    | '/_shell/holidays'
    | '/_shell/imports'
    | '/_shell/incentives'
    | '/_shell/leaderboard'
    | '/_shell/leave'
    | '/_shell/live'
    | '/_shell/mission-control'
    | '/_shell/notifications'
    | '/_shell/office-networks'
    | '/_shell/operations'
    | '/_shell/payroll'
    | '/_shell/people'
    | '/_shell/performance'
    | '/_shell/policies'
    | '/_shell/presence'
    | '/_shell/profile'
    | '/_shell/reports'
    | '/_shell/scoring'
    | '/_shell/settings'
    | '/_shell/shifts'
    | '/_shell/team'
    | '/_shell/workspace'
    | '/_shell/agents/new'
    | '/_shell/clients/new'
    | '/_shell/closers/new'
    | '/_shell/followups/$followUpId'
    | '/_shell/leads/$leadId'
    | '/_shell/leads/new'
    | '/api/diag/login'
    | '/_shell/agents/'
    | '/_shell/clients/'
    | '/_shell/closers/'
    | '/_shell/followups/'
    | '/_shell/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  OfficeTvRoute: typeof OfficeTvRoute
  ApiDiagLoginRoute: typeof ApiDiagLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-tv': {
      id: '/office-tv'
      path: '/office-tv'
      fullPath: '/office-tv'
      preLoaderRoute: typeof OfficeTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/assignments': {
      id: '/_shell/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof ShellAssignmentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/attendance': {
      id: '/_shell/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof ShellAttendanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/audit': {
      id: '/_shell/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ShellAuditRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/closer-hub': {
      id: '/_shell/closer-hub'
      path: '/closer-hub'
      fullPath: '/closer-hub'
      preLoaderRoute: typeof ShellCloserHubRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/company': {
      id: '/_shell/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof ShellCompanyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/employees': {
      id: '/_shell/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof ShellEmployeesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/exports': {
      id: '/_shell/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ShellExportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/holidays': {
      id: '/_shell/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof ShellHolidaysRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/imports': {
      id: '/_shell/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ShellImportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/incentives': {
      id: '/_shell/incentives'
      path: '/incentives'
      fullPath: '/incentives'
      preLoaderRoute: typeof ShellIncentivesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leaderboard': {
      id: '/_shell/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof ShellLeaderboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leave': {
      id: '/_shell/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof ShellLeaveRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/live': {
      id: '/_shell/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof ShellLiveRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/mission-control': {
      id: '/_shell/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof ShellMissionControlRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/office-networks': {
      id: '/_shell/office-networks'
      path: '/office-networks'
      fullPath: '/office-networks'
      preLoaderRoute: typeof ShellOfficeNetworksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/operations': {
      id: '/_shell/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof ShellOperationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/payroll': {
      id: '/_shell/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof ShellPayrollRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/people': {
      id: '/_shell/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof ShellPeopleRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/performance': {
      id: '/_shell/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof ShellPerformanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/policies': {
      id: '/_shell/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof ShellPoliciesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/presence': {
      id: '/_shell/presence'
      path: '/presence'
      fullPath: '/presence'
      preLoaderRoute: typeof ShellPresenceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/scoring': {
      id: '/_shell/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ShellScoringRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/shifts': {
      id: '/_shell/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShellShiftsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/team': {
      id: '/_shell/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ShellTeamRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workspace': {
      id: '/_shell/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof ShellWorkspaceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/agents/': {
      id: '/_shell/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof ShellAgentsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/agents/new': {
      id: '/_shell/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof ShellAgentsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clients/': {
      id: '/_shell/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ShellClientsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clients/new': {
      id: '/_shell/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ShellClientsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/closers/': {
      id: '/_shell/closers/'
      path: '/closers'
      fullPath: '/closers/'
      preLoaderRoute: typeof ShellClosersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/closers/new': {
      id: '/_shell/closers/new'
      path: '/closers/new'
      fullPath: '/closers/new'
      preLoaderRoute: typeof ShellClosersNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/followups/': {
      id: '/_shell/followups/'
      path: '/followups'
      fullPath: '/followups/'
      preLoaderRoute: typeof ShellFollowupsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/followups/$followUpId': {
      id: '/_shell/followups/$followUpId'
      path: '/followups/$followUpId'
      fullPath: '/followups/$followUpId'
      preLoaderRoute: typeof ShellFollowupsFollowUpIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leads/': {
      id: '/_shell/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof ShellLeadsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leads/$leadId': {
      id: '/_shell/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof ShellLeadsLeadIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leads/new': {
      id: '/_shell/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof ShellLeadsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/diag/login': {
      id: '/api/diag/login'
      path: '/api/diag/login'
      fullPath: '/api/diag/login'
      preLoaderRoute: typeof ApiDiagLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellAssignmentsRoute: typeof ShellAssignmentsRoute
  ShellAttendanceRoute: typeof ShellAttendanceRoute
  ShellAuditRoute: typeof ShellAuditRoute
  ShellCloserHubRoute: typeof ShellCloserHubRoute
  ShellCompanyRoute: typeof ShellCompanyRoute
  ShellEmployeesRoute: typeof ShellEmployeesRoute
  ShellExportsRoute: typeof ShellExportsRoute
  ShellHolidaysRoute: typeof ShellHolidaysRoute
  ShellImportsRoute: typeof ShellImportsRoute
  ShellIncentivesRoute: typeof ShellIncentivesRoute
  ShellLeaderboardRoute: typeof ShellLeaderboardRoute
  ShellLeaveRoute: typeof ShellLeaveRoute
  ShellLiveRoute: typeof ShellLiveRoute
  ShellMissionControlRoute: typeof ShellMissionControlRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellOfficeNetworksRoute: typeof ShellOfficeNetworksRoute
  ShellOperationsRoute: typeof ShellOperationsRoute
  ShellPayrollRoute: typeof ShellPayrollRoute
  ShellPeopleRoute: typeof ShellPeopleRoute
  ShellPerformanceRoute: typeof ShellPerformanceRoute
  ShellPoliciesRoute: typeof ShellPoliciesRoute
  ShellPresenceRoute: typeof ShellPresenceRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellScoringRoute: typeof ShellScoringRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellShiftsRoute: typeof ShellShiftsRoute
  ShellTeamRoute: typeof ShellTeamRoute
  ShellWorkspaceRoute: typeof ShellWorkspaceRoute
  ShellAgentsNewRoute: typeof ShellAgentsNewRoute
  ShellClientsNewRoute: typeof ShellClientsNewRoute
  ShellClosersNewRoute: typeof ShellClosersNewRoute
  ShellFollowupsFollowUpIdRoute: typeof ShellFollowupsFollowUpIdRoute
  ShellLeadsLeadIdRoute: typeof ShellLeadsLeadIdRoute
  ShellLeadsNewRoute: typeof ShellLeadsNewRoute
  ShellAgentsIndexRoute: typeof ShellAgentsIndexRoute
  ShellClientsIndexRoute: typeof ShellClientsIndexRoute
  ShellClosersIndexRoute: typeof ShellClosersIndexRoute
  ShellFollowupsIndexRoute: typeof ShellFollowupsIndexRoute
  ShellLeadsIndexRoute: typeof ShellLeadsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAssignmentsRoute: ShellAssignmentsRoute,
  ShellAttendanceRoute: ShellAttendanceRoute,
  ShellAuditRoute: ShellAuditRoute,
  ShellCloserHubRoute: ShellCloserHubRoute,
  ShellCompanyRoute: ShellCompanyRoute,
  ShellEmployeesRoute: ShellEmployeesRoute,
  ShellExportsRoute: ShellExportsRoute,
  ShellHolidaysRoute: ShellHolidaysRoute,
  ShellImportsRoute: ShellImportsRoute,
  ShellIncentivesRoute: ShellIncentivesRoute,
  ShellLeaderboardRoute: ShellLeaderboardRoute,
  ShellLeaveRoute: ShellLeaveRoute,
  ShellLiveRoute: ShellLiveRoute,
  ShellMissionControlRoute: ShellMissionControlRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellOfficeNetworksRoute: ShellOfficeNetworksRoute,
  ShellOperationsRoute: ShellOperationsRoute,
  ShellPayrollRoute: ShellPayrollRoute,
  ShellPeopleRoute: ShellPeopleRoute,
  ShellPerformanceRoute: ShellPerformanceRoute,
  ShellPoliciesRoute: ShellPoliciesRoute,
  ShellPresenceRoute: ShellPresenceRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellScoringRoute: ShellScoringRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellShiftsRoute: ShellShiftsRoute,
  ShellTeamRoute: ShellTeamRoute,
  ShellWorkspaceRoute: ShellWorkspaceRoute,
  ShellAgentsNewRoute: ShellAgentsNewRoute,
  ShellClientsNewRoute: ShellClientsNewRoute,
  ShellClosersNewRoute: ShellClosersNewRoute,
  ShellFollowupsFollowUpIdRoute: ShellFollowupsFollowUpIdRoute,
  ShellLeadsLeadIdRoute: ShellLeadsLeadIdRoute,
  ShellLeadsNewRoute: ShellLeadsNewRoute,
  ShellAgentsIndexRoute: ShellAgentsIndexRoute,
  ShellClientsIndexRoute: ShellClientsIndexRoute,
  ShellClosersIndexRoute: ShellClosersIndexRoute,
  ShellFollowupsIndexRoute: ShellFollowupsIndexRoute,
  ShellLeadsIndexRoute: ShellLeadsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  OfficeTvRoute: OfficeTvRoute,
  ApiDiagLoginRoute: ApiDiagLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
