/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAssignmentsRouteImport } from './routes/_shell.assignments'
import { Route as ShellAttendanceRouteImport } from './routes/_shell.attendance'
import { Route as ShellAuditRouteImport } from './routes/_shell.audit'
import { Route as ShellAvatarStudioRouteImport } from './routes/_shell.avatar-studio'
import { Route as ShellCloserHubRouteImport } from './routes/_shell.closer-hub'
import { Route as ShellEmployeesRouteImport } from './routes/_shell.employees'
import { Route as ShellExportsRouteImport } from './routes/_shell.exports'
import { Route as ShellHolidaysRouteImport } from './routes/_shell.holidays'
import { Route as ShellImportsRouteImport } from './routes/_shell.imports'
import { Route as ShellLeaderboardRouteImport } from './routes/_shell.leaderboard'
import { Route as ShellLeaveRouteImport } from './routes/_shell.leave'
import { Route as ShellMissionControlRouteImport } from './routes/_shell.mission-control'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellPayrollRouteImport } from './routes/_shell.payroll'
import { Route as ShellPeopleRouteImport } from './routes/_shell.people'
import { Route as ShellPresenceRouteImport } from './routes/_shell.presence'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellTeamRouteImport } from './routes/_shell.team'
import { Route as ShellWorkspaceRouteImport } from './routes/_shell.workspace'
import { Route as ShellAgentsIndexRouteImport } from './routes/_shell.agents.index'
import { Route as ShellAgentsNewRouteImport } from './routes/_shell.agents.new'
import { Route as ShellClientsIndexRouteImport } from './routes/_shell.clients.index'
import { Route as ShellClientsNewRouteImport } from './routes/_shell.clients.new'
import { Route as ShellClosersIndexRouteImport } from './routes/_shell.closers.index'
import { Route as ShellClosersNewRouteImport } from './routes/_shell.closers.new'
import { Route as ShellFollowupsIndexRouteImport } from './routes/_shell.followups.index'
import { Route as ShellFollowupsFollowUpIdRouteImport } from './routes/_shell.followups.$followUpId'
import { Route as ShellLeadsIndexRouteImport } from './routes/_shell.leads.index'
import { Route as ShellLeadsLeadIdRouteImport } from './routes/_shell.leads.$leadId'
import { Route as ShellLeadsNewRouteImport } from './routes/_shell.leads.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAssignmentsRoute = ShellAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAttendanceRoute = ShellAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuditRoute = ShellAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAvatarStudioRoute = ShellAvatarStudioRouteImport.update({
  id: '/avatar-studio',
  path: '/avatar-studio',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCloserHubRoute = ShellCloserHubRouteImport.update({
  id: '/closer-hub',
  path: '/closer-hub',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEmployeesRoute = ShellEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExportsRoute = ShellExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHolidaysRoute = ShellHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => ShellRoute,
} as any)
const ShellImportsRoute = ShellImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeaderboardRoute = ShellLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeaveRoute = ShellLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMissionControlRoute = ShellMissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPayrollRoute = ShellPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPeopleRoute = ShellPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPresenceRoute = ShellPresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTeamRoute = ShellTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkspaceRoute = ShellWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAgentsIndexRoute = ShellAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAgentsNewRoute = ShellAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClientsIndexRoute = ShellClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClientsNewRoute = ShellClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClosersIndexRoute = ShellClosersIndexRouteImport.update({
  id: '/closers/',
  path: '/closers/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClosersNewRoute = ShellClosersNewRouteImport.update({
  id: '/closers/new',
  path: '/closers/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFollowupsIndexRoute = ShellFollowupsIndexRouteImport.update({
  id: '/followups/',
  path: '/followups/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFollowupsFollowUpIdRoute =
  ShellFollowupsFollowUpIdRouteImport.update({
    id: '/followups/$followUpId',
    path: '/followups/$followUpId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellLeadsIndexRoute = ShellLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeadsLeadIdRoute = ShellLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeadsNewRoute = ShellLeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof ShellAssignmentsRoute
  '/attendance': typeof ShellAttendanceRoute
  '/audit': typeof ShellAuditRoute
  '/avatar-studio': typeof ShellAvatarStudioRoute
  '/closer-hub': typeof ShellCloserHubRoute
  '/employees': typeof ShellEmployeesRoute
  '/exports': typeof ShellExportsRoute
  '/holidays': typeof ShellHolidaysRoute
  '/imports': typeof ShellImportsRoute
  '/leaderboard': typeof ShellLeaderboardRoute
  '/leave': typeof ShellLeaveRoute
  '/mission-control': typeof ShellMissionControlRoute
  '/notifications': typeof ShellNotificationsRoute
  '/payroll': typeof ShellPayrollRoute
  '/people': typeof ShellPeopleRoute
  '/presence': typeof ShellPresenceRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/team': typeof ShellTeamRoute
  '/workspace': typeof ShellWorkspaceRoute
  '/agents/new': typeof ShellAgentsNewRoute
  '/clients/new': typeof ShellClientsNewRoute
  '/closers/new': typeof ShellClosersNewRoute
  '/followups/$followUpId': typeof ShellFollowupsFollowUpIdRoute
  '/leads/$leadId': typeof ShellLeadsLeadIdRoute
  '/leads/new': typeof ShellLeadsNewRoute
  '/agents/': typeof ShellAgentsIndexRoute
  '/clients/': typeof ShellClientsIndexRoute
  '/closers/': typeof ShellClosersIndexRoute
  '/followups/': typeof ShellFollowupsIndexRoute
  '/leads/': typeof ShellLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof ShellAssignmentsRoute
  '/attendance': typeof ShellAttendanceRoute
  '/audit': typeof ShellAuditRoute
  '/avatar-studio': typeof ShellAvatarStudioRoute
  '/closer-hub': typeof ShellCloserHubRoute
  '/employees': typeof ShellEmployeesRoute
  '/exports': typeof ShellExportsRoute
  '/holidays': typeof ShellHolidaysRoute
  '/imports': typeof ShellImportsRoute
  '/leaderboard': typeof ShellLeaderboardRoute
  '/leave': typeof ShellLeaveRoute
  '/mission-control': typeof ShellMissionControlRoute
  '/notifications': typeof ShellNotificationsRoute
  '/payroll': typeof ShellPayrollRoute
  '/people': typeof ShellPeopleRoute
  '/presence': typeof ShellPresenceRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/team': typeof ShellTeamRoute
  '/workspace': typeof ShellWorkspaceRoute
  '/agents/new': typeof ShellAgentsNewRoute
  '/clients/new': typeof ShellClientsNewRoute
  '/closers/new': typeof ShellClosersNewRoute
  '/followups/$followUpId': typeof ShellFollowupsFollowUpIdRoute
  '/leads/$leadId': typeof ShellLeadsLeadIdRoute
  '/leads/new': typeof ShellLeadsNewRoute
  '/agents': typeof ShellAgentsIndexRoute
  '/clients': typeof ShellClientsIndexRoute
  '/closers': typeof ShellClosersIndexRoute
  '/followups': typeof ShellFollowupsIndexRoute
  '/leads': typeof ShellLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/assignments': typeof ShellAssignmentsRoute
  '/_shell/attendance': typeof ShellAttendanceRoute
  '/_shell/audit': typeof ShellAuditRoute
  '/_shell/avatar-studio': typeof ShellAvatarStudioRoute
  '/_shell/closer-hub': typeof ShellCloserHubRoute
  '/_shell/employees': typeof ShellEmployeesRoute
  '/_shell/exports': typeof ShellExportsRoute
  '/_shell/holidays': typeof ShellHolidaysRoute
  '/_shell/imports': typeof ShellImportsRoute
  '/_shell/leaderboard': typeof ShellLeaderboardRoute
  '/_shell/leave': typeof ShellLeaveRoute
  '/_shell/mission-control': typeof ShellMissionControlRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/payroll': typeof ShellPayrollRoute
  '/_shell/people': typeof ShellPeopleRoute
  '/_shell/presence': typeof ShellPresenceRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/team': typeof ShellTeamRoute
  '/_shell/workspace': typeof ShellWorkspaceRoute
  '/_shell/agents/new': typeof ShellAgentsNewRoute
  '/_shell/clients/new': typeof ShellClientsNewRoute
  '/_shell/closers/new': typeof ShellClosersNewRoute
  '/_shell/followups/$followUpId': typeof ShellFollowupsFollowUpIdRoute
  '/_shell/leads/$leadId': typeof ShellLeadsLeadIdRoute
  '/_shell/leads/new': typeof ShellLeadsNewRoute
  '/_shell/agents/': typeof ShellAgentsIndexRoute
  '/_shell/clients/': typeof ShellClientsIndexRoute
  '/_shell/closers/': typeof ShellClosersIndexRoute
  '/_shell/followups/': typeof ShellFollowupsIndexRoute
  '/_shell/leads/': typeof ShellLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/attendance'
    | '/audit'
    | '/avatar-studio'
    | '/closer-hub'
    | '/employees'
    | '/exports'
    | '/holidays'
    | '/imports'
    | '/leaderboard'
    | '/leave'
    | '/mission-control'
    | '/notifications'
    | '/payroll'
    | '/people'
    | '/presence'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/team'
    | '/workspace'
    | '/agents/new'
    | '/clients/new'
    | '/closers/new'
    | '/followups/$followUpId'
    | '/leads/$leadId'
    | '/leads/new'
    | '/agents/'
    | '/clients/'
    | '/closers/'
    | '/followups/'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/attendance'
    | '/audit'
    | '/avatar-studio'
    | '/closer-hub'
    | '/employees'
    | '/exports'
    | '/holidays'
    | '/imports'
    | '/leaderboard'
    | '/leave'
    | '/mission-control'
    | '/notifications'
    | '/payroll'
    | '/people'
    | '/presence'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/team'
    | '/workspace'
    | '/agents/new'
    | '/clients/new'
    | '/closers/new'
    | '/followups/$followUpId'
    | '/leads/$leadId'
    | '/leads/new'
    | '/agents'
    | '/clients'
    | '/closers'
    | '/followups'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/assignments'
    | '/_shell/attendance'
    | '/_shell/audit'
    | '/_shell/avatar-studio'
    | '/_shell/closer-hub'
    | '/_shell/employees'
    | '/_shell/exports'
    | '/_shell/holidays'
    | '/_shell/imports'
    | '/_shell/leaderboard'
    | '/_shell/leave'
    | '/_shell/mission-control'
    | '/_shell/notifications'
    | '/_shell/payroll'
    | '/_shell/people'
    | '/_shell/presence'
    | '/_shell/profile'
    | '/_shell/reports'
    | '/_shell/settings'
    | '/_shell/team'
    | '/_shell/workspace'
    | '/_shell/agents/new'
    | '/_shell/clients/new'
    | '/_shell/closers/new'
    | '/_shell/followups/$followUpId'
    | '/_shell/leads/$leadId'
    | '/_shell/leads/new'
    | '/_shell/agents/'
    | '/_shell/clients/'
    | '/_shell/closers/'
    | '/_shell/followups/'
    | '/_shell/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/assignments': {
      id: '/_shell/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof ShellAssignmentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/attendance': {
      id: '/_shell/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof ShellAttendanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/audit': {
      id: '/_shell/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ShellAuditRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/avatar-studio': {
      id: '/_shell/avatar-studio'
      path: '/avatar-studio'
      fullPath: '/avatar-studio'
      preLoaderRoute: typeof ShellAvatarStudioRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/closer-hub': {
      id: '/_shell/closer-hub'
      path: '/closer-hub'
      fullPath: '/closer-hub'
      preLoaderRoute: typeof ShellCloserHubRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/employees': {
      id: '/_shell/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof ShellEmployeesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/exports': {
      id: '/_shell/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ShellExportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/holidays': {
      id: '/_shell/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof ShellHolidaysRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/imports': {
      id: '/_shell/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ShellImportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leaderboard': {
      id: '/_shell/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof ShellLeaderboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leave': {
      id: '/_shell/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof ShellLeaveRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/mission-control': {
      id: '/_shell/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof ShellMissionControlRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/payroll': {
      id: '/_shell/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof ShellPayrollRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/people': {
      id: '/_shell/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof ShellPeopleRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/presence': {
      id: '/_shell/presence'
      path: '/presence'
      fullPath: '/presence'
      preLoaderRoute: typeof ShellPresenceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/team': {
      id: '/_shell/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ShellTeamRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workspace': {
      id: '/_shell/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof ShellWorkspaceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/agents/': {
      id: '/_shell/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof ShellAgentsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/agents/new': {
      id: '/_shell/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof ShellAgentsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clients/': {
      id: '/_shell/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ShellClientsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clients/new': {
      id: '/_shell/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ShellClientsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/closers/': {
      id: '/_shell/closers/'
      path: '/closers'
      fullPath: '/closers/'
      preLoaderRoute: typeof ShellClosersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/closers/new': {
      id: '/_shell/closers/new'
      path: '/closers/new'
      fullPath: '/closers/new'
      preLoaderRoute: typeof ShellClosersNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/followups/': {
      id: '/_shell/followups/'
      path: '/followups'
      fullPath: '/followups/'
      preLoaderRoute: typeof ShellFollowupsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/followups/$followUpId': {
      id: '/_shell/followups/$followUpId'
      path: '/followups/$followUpId'
      fullPath: '/followups/$followUpId'
      preLoaderRoute: typeof ShellFollowupsFollowUpIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leads/': {
      id: '/_shell/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof ShellLeadsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leads/$leadId': {
      id: '/_shell/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof ShellLeadsLeadIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leads/new': {
      id: '/_shell/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof ShellLeadsNewRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAssignmentsRoute: typeof ShellAssignmentsRoute
  ShellAttendanceRoute: typeof ShellAttendanceRoute
  ShellAuditRoute: typeof ShellAuditRoute
  ShellAvatarStudioRoute: typeof ShellAvatarStudioRoute
  ShellCloserHubRoute: typeof ShellCloserHubRoute
  ShellEmployeesRoute: typeof ShellEmployeesRoute
  ShellExportsRoute: typeof ShellExportsRoute
  ShellHolidaysRoute: typeof ShellHolidaysRoute
  ShellImportsRoute: typeof ShellImportsRoute
  ShellLeaderboardRoute: typeof ShellLeaderboardRoute
  ShellLeaveRoute: typeof ShellLeaveRoute
  ShellMissionControlRoute: typeof ShellMissionControlRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellPayrollRoute: typeof ShellPayrollRoute
  ShellPeopleRoute: typeof ShellPeopleRoute
  ShellPresenceRoute: typeof ShellPresenceRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTeamRoute: typeof ShellTeamRoute
  ShellWorkspaceRoute: typeof ShellWorkspaceRoute
  ShellAgentsNewRoute: typeof ShellAgentsNewRoute
  ShellClientsNewRoute: typeof ShellClientsNewRoute
  ShellClosersNewRoute: typeof ShellClosersNewRoute
  ShellFollowupsFollowUpIdRoute: typeof ShellFollowupsFollowUpIdRoute
  ShellLeadsLeadIdRoute: typeof ShellLeadsLeadIdRoute
  ShellLeadsNewRoute: typeof ShellLeadsNewRoute
  ShellAgentsIndexRoute: typeof ShellAgentsIndexRoute
  ShellClientsIndexRoute: typeof ShellClientsIndexRoute
  ShellClosersIndexRoute: typeof ShellClosersIndexRoute
  ShellFollowupsIndexRoute: typeof ShellFollowupsIndexRoute
  ShellLeadsIndexRoute: typeof ShellLeadsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAssignmentsRoute: ShellAssignmentsRoute,
  ShellAttendanceRoute: ShellAttendanceRoute,
  ShellAuditRoute: ShellAuditRoute,
  ShellAvatarStudioRoute: ShellAvatarStudioRoute,
  ShellCloserHubRoute: ShellCloserHubRoute,
  ShellEmployeesRoute: ShellEmployeesRoute,
  ShellExportsRoute: ShellExportsRoute,
  ShellHolidaysRoute: ShellHolidaysRoute,
  ShellImportsRoute: ShellImportsRoute,
  ShellLeaderboardRoute: ShellLeaderboardRoute,
  ShellLeaveRoute: ShellLeaveRoute,
  ShellMissionControlRoute: ShellMissionControlRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellPayrollRoute: ShellPayrollRoute,
  ShellPeopleRoute: ShellPeopleRoute,
  ShellPresenceRoute: ShellPresenceRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTeamRoute: ShellTeamRoute,
  ShellWorkspaceRoute: ShellWorkspaceRoute,
  ShellAgentsNewRoute: ShellAgentsNewRoute,
  ShellClientsNewRoute: ShellClientsNewRoute,
  ShellClosersNewRoute: ShellClosersNewRoute,
  ShellFollowupsFollowUpIdRoute: ShellFollowupsFollowUpIdRoute,
  ShellLeadsLeadIdRoute: ShellLeadsLeadIdRoute,
  ShellLeadsNewRoute: ShellLeadsNewRoute,
  ShellAgentsIndexRoute: ShellAgentsIndexRoute,
  ShellClientsIndexRoute: ShellClientsIndexRoute,
  ShellClosersIndexRoute: ShellClosersIndexRoute,
  ShellFollowupsIndexRoute: ShellFollowupsIndexRoute,
  ShellLeadsIndexRoute: ShellLeadsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
