/**
 * Officeverse — profile-photo storage abstraction (Phase 19).
 *
 * PRIVATE storage — employee photos are internal company data. They are NEVER
 * served from an unauthenticated public URL; the client fetches the bytes
 * through an authenticated server function.
 *
 * Providers (chosen by PHOTO_STORAGE, reusing the existing config names):
 *   - "local" → durable files under PHOTO_LOCAL_DIR (default ./storage/photos)
 *   - anything else (s3/r2/supabase) is not implemented here → in-memory dev store
 *
 * Path safety reuses `resolveDocumentPath` from the salary-slip storage module
 * (rejects absolute keys, `..`, `.` segments, NUL; resolves under the root).
 * Keys are always server-generated by `safePhotoKey`.
 */
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { resolve, sep } from "node:path";
import { config, env } from "../env";
import { resolveDocumentPath } from "./salary-slip-storage";

export interface PhotoStore {
  readonly kind: string;
  put(key: string, bytes: Uint8Array): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
  exists(key: string): Promise<boolean>;
  deleteKey(key: string): Promise<void>;
}

class MemoryPhotoStore implements PhotoStore {
  readonly kind = "memory";
  private readonly map = new Map<string, Uint8Array>();
  async put(key: string, bytes: Uint8Array): Promise<void> {
    if (/(^|[\\/])\.\.([\\/]|$)/.test(key) || key.startsWith("/")) throw new Error("invalid key");
    this.map.set(key, Uint8Array.from(bytes));
  }
  async get(key: string): Promise<Uint8Array | null> {
    const v = this.map.get(key);
    return v ? Uint8Array.from(v) : null;
  }
  async exists(key: string): Promise<boolean> {
    return this.map.has(key);
  }
  async deleteKey(key: string): Promise<void> {
    this.map.delete(key);
  }
}

class FilesystemPhotoStore implements PhotoStore {
  readonly kind = "filesystem";
  constructor(private readonly root: string) {}
  private path(key: string): string {
    return resolveDocumentPath(this.root, key);
  }
  async put(key: string, bytes: Uint8Array): Promise<void> {
    const abs = this.path(key);
    await mkdir(abs.slice(0, abs.lastIndexOf(sep)), { recursive: true });
    await writeFile(abs, Buffer.from(bytes));
  }
  async get(key: string): Promise<Uint8Array | null> {
    try {
      return new Uint8Array(await readFile(this.path(key)));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
      throw err;
    }
  }
  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.path(key));
      return true;
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return false;
      throw err;
    }
  }
  async deleteKey(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }
}

let cached: { key: string; store: PhotoStore } | null = null;

export function getPhotoStore(): PhotoStore {
  const provider = (env("PHOTO_STORAGE") ?? "local").toLowerCase();
  const root = provider === "local" ? config.photoLocalDir() : "";
  const cacheKey = `${provider}:${root}`;
  if (cached && cached.key === cacheKey) return cached.store;
  const store: PhotoStore =
    provider === "local"
      ? new FilesystemPhotoStore(resolve(root || "./storage/photos"))
      : new MemoryPhotoStore();
  cached = { key: cacheKey, store };
  return store;
}

export function __resetPhotoStore(): void {
  cached = null;
}

export function describePhotoStorage(): { provider: string; durable: boolean } {
  const provider = (env("PHOTO_STORAGE") ?? "local").toLowerCase();
  return { provider, durable: provider === "local" };
}
