/**
 * Officeverse — profile-photo storage abstraction (Phase 19 + Phase 24).
 *
 * PRIVATE storage — employee photos are internal company data. They are NEVER
 * served from an unauthenticated public URL; the client fetches the bytes
 * through an authenticated server function.
 *
 * Providers (chosen by PHOTO_STORAGE, reusing the existing config names):
 *   - "local"    → durable files under PHOTO_LOCAL_DIR (default ./storage/photos)
 *                  — GoDaddy / local dev. NOT available on Vercel (no writable
 *                  filesystem), where it's upgraded to "database" instead
 *                  (see below) rather than silently falling back to memory.
 *   - "database" → durable rows in the existing MySQL `storage_blobs` table
 *                  (see server/db-blob-store.ts) — the Vercel-safe
 *                  default. Selectable explicitly anywhere too.
 *   - anything else (s3/r2/supabase) is not implemented here → in-memory dev store
 *
 * Path safety reuses `resolveDocumentPath` from the salary-slip storage module
 * (rejects absolute keys, `..`, `.` segments, NUL; resolves under the root).
 * Keys are always server-generated by `safePhotoKey`.
 */
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { resolve, sep } from "node:path";
import { isDbConfigured } from "@/lib/db";
import { config, env, isVercel } from "../env";
import { DatabaseBlobStore } from "../db-blob-store";
import { resolveDocumentPath } from "./salary-slip-storage";

export interface PhotoStore {
  readonly kind: string;
  put(key: string, bytes: Uint8Array): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
  exists(key: string): Promise<boolean>;
  deleteKey(key: string): Promise<void>;
}

class MemoryPhotoStore implements PhotoStore {
  readonly kind = "memory";
  private readonly map = new Map<string, Uint8Array>();
  async put(key: string, bytes: Uint8Array): Promise<void> {
    if (/(^|[\\/])\.\.([\\/]|$)/.test(key) || key.startsWith("/")) throw new Error("invalid key");
    this.map.set(key, Uint8Array.from(bytes));
  }
  async get(key: string): Promise<Uint8Array | null> {
    const v = this.map.get(key);
    return v ? Uint8Array.from(v) : null;
  }
  async exists(key: string): Promise<boolean> {
    return this.map.has(key);
  }
  async deleteKey(key: string): Promise<void> {
    this.map.delete(key);
  }
}

class FilesystemPhotoStore implements PhotoStore {
  readonly kind = "filesystem";
  constructor(private readonly root: string) {}
  private path(key: string): string {
    return resolveDocumentPath(this.root, key);
  }
  async put(key: string, bytes: Uint8Array): Promise<void> {
    const abs = this.path(key);
    await mkdir(abs.slice(0, abs.lastIndexOf(sep)), { recursive: true });
    await writeFile(abs, Buffer.from(bytes));
  }
  async get(key: string): Promise<Uint8Array | null> {
    try {
      return new Uint8Array(await readFile(this.path(key)));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
      throw err;
    }
  }
  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.path(key));
      return true;
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return false;
      throw err;
    }
  }
  async deleteKey(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }
}

let cached: { key: string; store: PhotoStore } | null = null;

/**
 * Resolve which backend `getPhotoStore()` should actually use. Split out so
 * `describePhotoStorage()` (a status/diagnostics read) and `getPhotoStore()`
 * agree exactly on what's really in effect.
 */
function resolveBackend(): { kind: "local" | "database" | "memory"; cacheKey: string } {
  const provider = (env("PHOTO_STORAGE") ?? "local").toLowerCase();
  if (provider === "database") return { kind: "database", cacheKey: "database" };
  if (provider === "local") {
    // Vercel Functions have no writable persistent filesystem — "local"
    // would otherwise try to mkdir under process.cwd() (/var/task), which
    // is read-only and throws ENOENT. Upgrade to the durable database-backed
    // store instead of silently degrading to memory (which a cold start can
    // drop). Only when the DB itself isn't configured either — a dead-end
    // state where essentially nothing in the app works — is memory used, so
    // a photo upload never crashes even in that state.
    if (isVercel()) {
      if (isDbConfigured()) return { kind: "database", cacheKey: "database" };
      console.warn(
        "[photo-storage] PHOTO_STORAGE=local is not supported on Vercel and no database is configured — using the in-memory store (uploads will NOT survive a cold start).",
      );
      return { kind: "memory", cacheKey: "memory" };
    }
    return { kind: "local", cacheKey: `local:${config.photoLocalDir()}` };
  }
  // s3 / r2 / supabase — named but not implemented; unchanged pre-existing behavior.
  return { kind: "memory", cacheKey: "memory" };
}

export function getPhotoStore(): PhotoStore {
  const { kind, cacheKey } = resolveBackend();
  if (cached && cached.key === cacheKey) return cached.store;
  const store: PhotoStore =
    kind === "local"
      ? new FilesystemPhotoStore(resolve(config.photoLocalDir()))
      : kind === "database"
        ? new DatabaseBlobStore()
        : new MemoryPhotoStore();
  cached = { key: cacheKey, store };
  return store;
}

export function __resetPhotoStore(): void {
  cached = null;
}

export function describePhotoStorage(): { provider: string; durable: boolean } {
  const { kind } = resolveBackend();
  return { provider: kind, durable: kind !== "memory" };
}
